### ISSUE TITLE
php_beautifier [error] Token doesn't exist

### ISSUE THREAD

**Issue by mscarchilli** [akalongman/sublimetext-codeformatter#143] opened 2015-05-15 17:46 UTC
I get this error when trying to format PHP in some files (not all)

```
CodeFormatter

Format error:
May 15 19:45:-1 php_beautifier [error] Token doesn't exist
```

This is the code in particular that is causing the error for me currently:
```php
while ($i <= 1):
    $html .= 'text';
endwhile;
```
Sublime: ST3
OS: Win7
Plugin: v2.4.1 I believe.

**Comment by mscarchilli** [comment] 2015-05-15 17:57
This is the code in particular that is causing the error:

```php
while ($i <= 1):
	$html .= 'text';
endwhile;
```

**Comment by jennevdmeer** [comment] 2015-05-22 13:39
I get the same using the alternative namespace syntax
```PHP
namespace Space {
  ...
}
```
Works properly with `namespace Space;`

**Comment by jakebathman** [comment] 2015-10-01 15:46
Same error here, not sure of the cause in my file (not using alternative namespace syntax). Let me know what debug info I can provide.

**Comment by jakebathman** [comment] 2015-10-01 15:50
Just found my error, it was improper nesting of my class functions (an extra closing brace } in a function).

**Comment by akalongman** [comment] 2016-01-19 14:28
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)

**Closed by akalongman** 2016-01-19 14:28 UTC
Labels: bug, php

**Comment by jakebathman** [comment] 2016-01-19 14:39
Thanks @akalongman I'll give it a try when the update gets pushed to packagecontrol.io
