### ISSUE TITLE
PHP formatting with HTML (bug, reopened)

### ISSUE THREAD

**Issue by nekromoff** [akalongman/sublimetext-codeformatter#350] opened 2017-12-04 13:12 UTC
See what actually happens and why this should be treated as bug:
https://github.com/akalongman/sublimetext-codeformatter/issues/157#issuecomment-348958057

**Comment by thecotne** [comment] 2017-12-05 06:26
duplicate of #157

**Closed by thecotne** 2017-12-05 06:26 UTC
