### ISSUE TITLE
else goto new line for "k&r" indent_style

### ISSUE THREAD

**Issue by n00bik** [akalongman/sublimetext-codeformatter#133] opened 2015-02-26 14:24 UTC
i.e. was before
if ($attempt++ > 5) {
  die("\t\t\terror : max attempt limit reached.\n");
} else {
  $sleep_time+= $sleep_time;
  MyEcho("curl again after $sleep_time sec's.");
}

and now

if ($attempt++ > 5) {
  die("\t\t\terror : max attempt limit reached.\n");
} 
  else {
  $sleep_time+= $sleep_time;
 MyEcho("curl again after $sleep_time sec's.");
}

**Comment by CodyPChristian** [comment] 2015-03-28 22:45
Any update to this? Its aggravating to me and also PHPBeautifier itself does not break them onto separate lines. Anyone know what file/line is doing this within the plugin?

**Comment by rtorcato** [comment] 2015-03-31 15:56
my else statements look so weird. need a fix for this, but great plugin everything else looks great.

**Comment by cigzigwon** [comment] 2015-04-06 16:06
confirmed, also class gets newline even if set to false... this happened after I recompiled PHP on another machine

**Comment by jsabino** [comment] 2015-08-07 14:03
This issue is caused by the commit c407cc5f10

**Comment by cigzigwon** [comment] 2015-08-14 17:37
can we get this ?
obviously the hack to fix is...
<code>if (strtolower($this->getSetting('style')) == 'allman') { $this->oBeaut->addNewLineIndent(); }</code>

what it should of been since his fix broke k&r!

**Comment by akalongman** [comment] 2015-08-18 07:49
Send me pull request and I will merge it

**Comment by cigzigwon** [comment] 2015-08-18 18:57
After the fix is applied don't forget to set pear to false because pear defaults to allman for else statements.

**Comment by cigzigwon** [comment] 2016-01-12 14:53
Is my P.R. ever going to get merged? I updated meh box today stuck with this issue again. Pear is off and else still get shoved to new lines it needs the patch.

**Comment by akalongman** [comment] 2016-01-19 14:29
CodeFormatter updated to version 3.0.0
Maybe your problems solved
See [Release Notes](https://github.com/akalongman/sublimetext-codeformatter/blob/master/messages/3.0.0.txt)

**Closed by akalongman** 2016-01-19 14:29 UTC
Labels: php
