### ISSUE TITLE
Keyword "use" remove by the phpfmt

### ISSUE THREAD

**Issue by macOneOone** [akalongman/sublimetext-codeformatter#242] opened 2016-06-25 19:16 UTC
I'm using Laravel and phpfmt is removing the keyword "use" after the namespace declaration like:

```
namespace App\Http\Controllers;
use App\Customer as Customer;

```

and it's cleaning it for:
`
namespace App\Http\Controllers;
`

**Comment by hao203** [comment] 2016-10-30 09:05
Yes, I also have the same error

**Comment by macOneOone** [comment] 2016-10-30 18:04
I'm thinks it's not issue, but it prevents you from load unnecessary files or module. I did the same without any framework and i had the same result

**Comment by zezeron** [comment] 2016-12-30 15:18
+1

I'm waiting for your answers

**Comment by thecotne** [comment] 2017-01-01 21:02
this is expected behavior if you are not using `Customer` it will remove unused `use` statement 

![60835984](https://cloud.githubusercontent.com/assets/1606993/21583029/0c23ad88-d087-11e6-9333-7abb2c52d543.jpg)


closing as it's not a bug

**Closed by thecotne** 2017-01-01 21:02 UTC

**Comment by Raggok** [comment] 2020-05-06 19:04
BUt what if im using it on a function

**Comment by ddon** [comment] 2023-08-11 20:17
so far found one solution that if you add a comment at the end of the use statement and phpfmt leaves it as it:

use xxxxxx; // phpfmt:disable-line
