### ISSUE TITLE
<!-- commented text in HTML -->

### ISSUE THREAD

**Issue by babydeer** [akalongman/sublimetext-codeformatter#138] opened 2015-03-26 12:10 UTC
each time I use codeformatter my  comments expands..
ex. Before using codeformatter.
![screenshot 2015-03-26 13 07 51](https://cloud.githubusercontent.com/assets/11645355/6845849/277877f2-d3b9-11e4-8a4c-b5d90d320c78.png)
ex. After formatting 3 times.
![screenshot 2015-03-26 13 09 31](https://cloud.githubusercontent.com/assets/11645355/6845874/5e5d748e-d3b9-11e4-8fee-4bc345800ccb.png)

You get the idea.

**Comment by AjiMIde** [comment] 2015-05-19 02:08
I got the same problem now~Feel so sad : (

**Comment by jenil27** [comment] 2015-06-19 13:35
Same here..

**Comment by thecotne** [comment] 2015-08-24 13:30
it is fixed now
(can't reproduce)

**Closed by thecotne** 2015-08-24 13:30 UTC
